import {
  createContext,
  useContext,
  useEffect,
  useLayoutEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "en" | "vi" | "es";
export type ThemeMode = "light" | "dark";

const LANGUAGE_STORAGE_KEY = "tenshop-language";
const THEME_STORAGE_KEY = "tenshop-theme";

const en = {
  layout: {
    brandTagline: "Delicious | Flexible | Easy",
    nav: {
      home: "Home",
      shop: "Shop",
      community: "Community",
      chat: "Chat",
    },
    signIn: "Sign in",
    profile: "Profile",
    settings: "Settings",
    language: "Language",
    theme: "Mode",
    light: "Light",
    dark: "Dark",
    languageNames: {
      en: "English",
      vi: "Tiếng Việt",
      es: "Español",
    },
    signOut: "Sign out",
    signOutFailed: "Sign out failed",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    open: "Open",
    show: "Show",
    hide: "Hide",
    delete: "Delete",
    clear: "Clear",
    done: "Done",
    add: "Create",
    send: "Send",
    loading: "Loading...",
    loadingChat: "Loading chat...",
    working: "Working...",
    searching: "Searching...",
    adding: "Adding...",
    deleting: "Deleting...",
    sending: "Sending...",
    you: "You",
    admin: "Admin",
    email: "Email",
    password: "Password",
    phone: "Phone",
    fullName: "Full name",
    address: "Address",
    deliveryAddress: "Delivery address",
    noRecipient: "No recipient",
    notes: "Notes",
    subtotal: "Subtotal",
    tax: "Tax",
    shipping: "Shipping",
    total: "Total",
    status: "Status",
    placed: "Placed",
    items: "Items",
    description: "Description",
    properties: "Properties",
    emptyMessage: "Empty message",
    noImage: "No image",
    noImageAvailable: "No image available",
    noDescriptionYet: "No description added yet.",
    shownCount: (shown: number, total: number) => `${shown} / ${total} shown`,
    orderId: (id: string) => `Order #${id.slice(0, 8)}`,
    customerId: (id: string) => `Customer ${id.slice(0, 8)}`,
    orderCreated: (count: number) => `Order created with ${count} item(s).`,
    orderPreviewTotal: (total: string) => `Order total ${total}`,
    notesValue: (notes: string) => `Notes: ${notes}`,
    phoneValue: (phone: string) => `Phone: ${phone}`,
    deleteCartAria: (name: string) => `Delete ${name}`,
    removeItemAria: (name: string) => `Remove ${name}`,
  },
  status: {
    pending: "Pending",
    confirmed: "Confirmed",
    shipped: "Shipped",
    out_for_delivery: "On the way",
    packaging: "Packaging",
    delivered: "Delivered",
    cancelled: "Cancelled",
    archived: "Archive",
  },
  productImageField: {
    noImageSelected: "No image selected",
    pasteImageUrl: "Paste image URL here",
    uploading: "Uploading...",
    uploadImage: "Upload image",
    clear: "Clear",
    helperText: "Paste an image URL or upload a file to ImageKit.",
  },
  requireAdmin: {
    checking: "Checking admin...",
  },
  home: {
    heroBadge: "Smart grocery planning for everyday life",
    heroTitle: "Grocery shopping that feels organized, social, and actually useful.",
    heroDescription:
      "Fill carts, browse products, and share ideas with your community in one clean experience. Less friction, fewer forgotten items, and a better way to plan meals together.",
    startShopping: "Start Shopping",
    signInToStart: "Sign in to Start",
    exploreCommunity: "Explore Community",
    statFastTitle: "Fast",
    statFastDesc: "Quick cart setup",
    statSimpleTitle: "Simple",
    statSimpleDesc: "Clean product browsing",
    statSocialTitle: "Social",
    statSocialDesc: "Community-driven ideas",
    flowTitle: "This week's flow",
    flowDescription: "A better shopping experience from planning to checkout.",
    live: "Live",
    step1Title: "1. Discover products",
    step1Desc: "Browse a clean product grid and add items in seconds.",
    step2Title: "2. Build your cart",
    step2Desc: "Keep your grocery plan organized with personal shopping carts.",
    step3Title: "3. Learn from community",
    step3Desc: "Share recipes, tips, and local finds with other shoppers.",
    cartsTitle: "Carts",
    cartsDesc: "Ready to order",
    shopTitle: "Shop",
    shopDesc: "Browse faster",
    postsTitle: "Posts",
    postsDesc: "Share ideas",
    card1Title: "Smarter shopping",
    card1Desc: "Turn scattered grocery notes into a clear cart you can actually use.",
    card2Title: "Community layer",
    card2Desc: "Discover recipes, recommendations, and ideas from people shopping like you.",
    card3Title: "Ready to grow",
    card3Desc:
      "A strong base for richer branding, categories, promotions, and real product storytelling.",
  },
  auth: {
    signIn: "Sign in",
    createAccount: "Create account",
    signUp: "Sign up",
    checkEmailMessage: "Check your email to confirm your account, then sign in.",
    somethingWentWrong: "Something went wrong",
    authSettingsNote:
      "Supabase Auth settings: enable Email provider and set Site URL + Redirect URLs for Netlify.",
  },
  community: {
    title: "Community",
    subtitle: "Public posts. Add comments or likes once your Figma flow is wired.",
    createPost: "Create post",
    titlePlaceholder: "Title",
    bodyPlaceholder: "Share a tip, recipe, or deal...",
    post: "Post",
  },
  chat: {
    title: "Chat",
    subtitle: "View your order chats and delete older ones.",
    orderRequestCreated: "Order request created.",
    deliveryAddressShared: "Delivery address shared",
    newUpdate: "New update",
    deleteConfirm: "Are you sure you want to delete this chat?",
    noChatsYet: "No chats yet",
    noChatsDescription: "Once you send an order request, it will appear here.",
    openChat: "Open chat",
  },
  shop: {
    title: "Shop",
    subtitle: "Click any item to view full details.",
    searchPlaceholder: "Search items by name, category, description, tag, or price...",
    noProductsAvailable: "No products available yet.",
    noProductsMatch: "No products match your search.",
    itemDetails: "Item details",
    addToCart: "Add to cart",
    addsTo: "Adds to:",
    selectedCartFallback: "Selected cart",
    createCartToStart: "Create a cart to start adding items.",
    yourCarts: "Your carts",
    selectedCart: "Selected cart",
    manageCartsSubtitle: "Open one cart to review it, or select several carts to delete.",
    searchCartsPlaceholder: "Search carts...",
    selectACart: "Select a cart...",
    defaultCartName: "My Cart",
    cartName: "Cart name",
    noCartsYet: "No carts yet.",
    noCartsMatch: "No carts match your search.",
    openFullCart: "Open full cart",
    cartItems: "Cart items",
    chooseCartToView: "Choose a cart to view its items.",
    noCartSelected: "No cart selected.",
    cartIsEmpty: "This cart is empty.",
    each: "each",
    inCart: (qty: number) => `${qty} in cart`,
    deleteCartTitle: "Delete cart",
    close: "Close",
    deleteCartConfirm: (name: string) => `Delete "${name}" and all of its items?`,
    selectCartFirst: "Select at least one cart first.",
    confirmDeleteSelectedCarts: (count: number) =>
      `Delete ${count} selected cart(s) and all of their items?`,
    createOrSelectCartFirst:
      "Create or select a cart first in the right panel before adding items.",
  },
  cartDetail: {
    title: "Your cart",
    subtitle: "Search products, add items, and update quantities.",
    addItems: "Add items",
    searchProducts: "Search products...",
    noMatches: "No matches.",
    uncategorized: "Uncategorized",
    cartItems: "Cart items",
    noItemsYet: "No items yet. Search above to add.",
    noPrice: "No price",
    remove: "Remove",
    orderTotal: "Order total",
    taxRate: "Tax 9%",
    deliveryAddress: "Delivery address",
    selectAddress: "Select address...",
    noteToAdmin: "Note to admin",
    notePlaceholder: "Optional note about delivery, substitutions, timing...",
    sendingOrder: "Sending order...",
    sendOrderRequest: "Send order request",
    cartEmptyAlert: "Your cart is empty.",
    addressRequiredAlert: "Please add or select a delivery address first.",
    couldNotCreateOrder: "Could not create order.",
    addressOption: (label: string, street: string, city: string) => `${label} - ${street}, ${city}`,
  },
  profile: {
    title: "Profile",
    account: "Account",
    saveProfile: "Save profile",
    addAddress: "Add address",
    labelPlaceholder: "Label (Home, Work)",
    recipientNamePlaceholder: "Recipient name",
    phonePlaceholder: "Phone",
    streetPlaceholder: "Street address",
    apartmentPlaceholder: "Apartment / unit",
    cityPlaceholder: "City",
    statePlaceholder: "State",
    zipPlaceholder: "ZIP code",
    countryPlaceholder: "Country",
    deliveryNotesPlaceholder: "Delivery notes",
    makeDefault: "Make this my default address",
    addAddressButton: "Add address",
    savedAddresses: "Saved addresses",
    noAddressesYet: "No addresses yet.",
    profileSaved: "Profile saved",
    cannotDeleteUsedAddress:
      "You cannot delete this address because it is already used by one or more orders. Please keep it for order history, or add a new address and set that one as default.",
    deleteAddressConfirm: "Delete this saved address?",
    makeDefaultButton: "Make default",
    defaultBadge: "Default",
    addressFallback: "Address",
    homeLabel: "Home",
  },
  orderDetail: {
    deleteConfirm: "Are you sure you want to delete this chat?",
    orderSummary: "Order summary",
    selectedDeliveryAddress: "Selected delivery address",
    orderChat: "Order chat",
    adminDeletedTitle: "This chat was deleted by admin.",
    adminDeletedBody: "You can still review it here. Do you want to delete it too?",
    deleteThisChat: "Delete this chat",
    addressChip: (label: string) => `Address: ${label}`,
    sendAddressTitle: "Send this address into chat",
    typeMessage: "Type a message...",
    noMessagesYet: "No messages yet.",
  },
  admin: {
    dashboardTitle: "Admin Dashboard",
    dashboardSubtitle: "Manage products and real customer order chats.",
    tabChat: "Chat",
    tabItems: "Items",
    addProduct: "Add product",
    productName: "Product name",
    productImage: "Product image",
    newProductImage: "New product image",
    priceUsd: "Price (USD)",
    tags: "Tags",
    tagsPlaceholder: "Fresh, Organic, 1 lb",
    tagsHint: "Separate each property with a comma.",
    description: "Description",
    descriptionPlaceholder: "One description for this item",
    addProductButton: "Add Product",
    products: "Products",
    searchItemsPlaceholder: "Search items by name, tag, description, or price...",
    noProductsYet: "No products yet.",
    noProductsMatch: "No products match your search.",
    productDescriptionPlaceholder: "Product description",
    pricePlaceholder: "Price",
    edit: "Edit",
    inStock: "In stock",
    outOfStock: "Out of stock",
    customerChats: "Customer Chats",
    customerChatsSubtitle:
      "Search by customer name or order, then use filters for date and total.",
    select: "Select",
    markShipped: "Mark delivered",
    searchCustomersPlaceholder: "Search customer name or order #...",
    openFilters: "Open filters",
    advancedFilters: "Advanced Filters",
    fromDate: "From date",
    toDate: "To date",
    minTotal: "Min total",
    maxTotal: "Max total",
    noOrderChats: "No order chats yet.",
    noChatsMatch: "No chats match the current filters.",
    selectChatFirst: "Select at least one chat first.",
    confirmMarkSelectedShipped:
      "Are you sure you want to mark the selected chats as delivered?",
    confirmHideSelectedChats:
      "Are you sure you want to remove the selected chats from the admin board only?",
    adminNotFound: "Could not find the signed-in admin.",
    confirmMarkCurrentShipped: "Are you sure you want to mark this order as delivered?",
    imageUploadFailed: "Image upload failed.",
    loadingChat: "Loading chat...",
    orderNotFound: "Order not found.",
    orderSummary: "Order summary",
    hideDetails: "Hide details",
    showDetails: "Show details",
    showAddress: "Show address",
    hideAddress: "Hide address",
    noAddressShared: "No address shared yet.",
    noMessagesYet: "No messages yet.",
    typeReply: "Type a reply and press Enter...",
  },
};

type AppCopy = typeof en;

const vi: AppCopy = {
  layout: {
    brandTagline: "Ngon | Linh hoạt | Dễ dàng",
    nav: {
      home: "Trang chủ",
      shop: "Cửa hàng",
      community: "Cộng đồng",
      chat: "Tin nhắn",
    },
    signIn: "Đăng nhập",
    profile: "Hồ sơ",
    settings: "Cài đặt",
    language: "Ngôn ngữ",
    theme: "Giao diện",
    light: "Sáng",
    dark: "Tối",
    languageNames: {
      en: "English",
      vi: "Tiếng Việt",
      es: "Español",
    },
    signOut: "Đăng xuất",
    signOutFailed: "Đăng xuất thất bại",
  },
  common: {
    save: "Lưu",
    cancel: "Hủy",
    close: "Đóng",
    open: "Mở",
    show: "Hiện",
    hide: "Ẩn",
    delete: "Xóa",
    clear: "Xóa bộ lọc",
    done: "Xong",
    add: "Thêm",
    send: "Gửi",
    loading: "Đang tải...",
    loadingChat: "Đang tải đoạn chat...",
    working: "Đang xử lý...",
    searching: "Đang tìm...",
    adding: "Đang thêm...",
    deleting: "Đang xóa...",
    sending: "Đang gửi...",
    you: "Bạn",
    admin: "Quản trị viên",
    email: "Email",
    password: "Mật khẩu",
    phone: "Số điện thoại",
    fullName: "Họ tên",
    address: "Địa chỉ",
    deliveryAddress: "Địa chỉ giao hàng",
    noRecipient: "Chưa có người nhận",
    notes: "Ghi chú",
    subtotal: "Tạm tính",
    tax: "Thuế",
    shipping: "Phí giao hàng",
    total: "Tổng cộng",
    status: "Trạng thái",
    placed: "Đặt lúc",
    items: "Mặt hàng",
    description: "Mô tả",
    properties: "Thuộc tính",
    emptyMessage: "Tin nhắn trống",
    noImage: "Không có hình",
    noImageAvailable: "Chưa có hình ảnh",
    noDescriptionYet: "Chưa có mô tả.",
    shownCount: (shown: number, total: number) => `${shown} / ${total} đang hiển thị`,
    orderId: (id: string) => `Đơn #${id.slice(0, 8)}`,
    customerId: (id: string) => `Khách ${id.slice(0, 8)}`,
    orderCreated: (count: number) => `Đơn hàng được tạo với ${count} mặt hàng.`,
    orderPreviewTotal: (total: string) => `Tổng đơn ${total}`,
    notesValue: (notes: string) => `Ghi chú: ${notes}`,
    phoneValue: (phone: string) => `Điện thoại: ${phone}`,
    deleteCartAria: (name: string) => `Xóa ${name}`,
    removeItemAria: (name: string) => `Bỏ ${name}`,
  },
  status: {
    pending: "Chờ xử lý",
    confirmed: "Đã xác nhận",
    shipped: "Đã gửi hàng",
    out_for_delivery: "Đang giao",
    packaging: "Packaging",
    delivered: "Đã giao",
    cancelled: "Đã hủy",
    archived: "Archive",
  },
  productImageField: {
    noImageSelected: "Chưa chọn hình",
    pasteImageUrl: "Dán URL hình ảnh vào đây",
    uploading: "Đang tải lên...",
    uploadImage: "Tải hình ảnh",
    clear: "Xóa",
    helperText: "Dán URL hình ảnh hoặc tải tệp lên ImageKit.",
  },
  requireAdmin: {
    checking: "Đang kiểm tra quyền quản trị...",
  },
  home: {
    heroBadge: "Lập kế hoạch đi chợ thông minh mỗi ngày",
    heroTitle: "Đi chợ được sắp xếp gọn gàng, có tính kết nối và thật sự hữu ích.",
    heroDescription:
      "Tạo giỏ hàng, xem sản phẩm và chia sẻ ý tưởng với cộng đồng trong một trải nghiệm gọn gàng. Giảm bối rối, ít quên đồ hơn và dễ cùng nhau lên kế hoạch bữa ăn.",
    startShopping: "Bắt đầu mua sắm",
    signInToStart: "Đăng nhập để bắt đầu",
    exploreCommunity: "Khám phá cộng đồng",
    statFastTitle: "Nhanh",
    statFastDesc: "Chuẩn bị giỏ hàng nhanh",
    statSimpleTitle: "Đơn giản",
    statSimpleDesc: "Xem sản phẩm gọn gàng",
    statSocialTitle: "Cộng đồng",
    statSocialDesc: "Ý tưởng từ mọi người",
    flowTitle: "Quy trình tuần này",
    flowDescription: "Trải nghiệm mua sắm tốt hơn từ lúc lập kế hoạch đến khi đặt hàng.",
    live: "Đang hoạt động",
    step1Title: "1. Khám phá sản phẩm",
    step1Desc: "Xem lưới sản phẩm gọn gàng và thêm mặt hàng trong vài giây.",
    step2Title: "2. Tạo giỏ hàng",
    step2Desc: "Giữ kế hoạch đi chợ gọn gàng với giỏ hàng cá nhân.",
    step3Title: "3. Học từ cộng đồng",
    step3Desc: "Chia sẻ công thức, mẹo và món hay với người mua sắm khác.",
    cartsTitle: "Giỏ hàng",
    cartsDesc: "Sẵn sàng đặt",
    shopTitle: "Mua sắm",
    shopDesc: "Xem nhanh hơn",
    postsTitle: "Bài viết",
    postsDesc: "Chia sẻ ý tưởng",
    card1Title: "Mua sắm thông minh hơn",
    card1Desc: "Biến ghi chú mua sắm rời rạc thành giỏ hàng rõ ràng để sử dụng.",
    card2Title: "Lớp cộng đồng",
    card2Desc: "Tìm công thức, gợi ý và ý tưởng từ những người mua sắm giống bạn.",
    card3Title: "Sẵn sàng phát triển",
    card3Desc:
      "Nền tảng tốt để mở rộng thương hiệu, danh mục, khuyến mãi và nội dung sản phẩm sau này.",
  },
  auth: {
    signIn: "Đăng nhập",
    createAccount: "Tạo tài khoản",
    signUp: "Đăng ký",
    checkEmailMessage: "Kiểm tra email để xác nhận tài khoản, sau đó đăng nhập.",
    somethingWentWrong: "Đã có lỗi xảy ra",
    authSettingsNote:
      "Cài đặt Supabase Auth: bật Email provider và đặt Site URL + Redirect URLs cho Netlify.",
  },
  community: {
    title: "Cộng đồng",
    subtitle: "Bài viết công khai. Có thể thêm bình luận hoặc thích sau khi Figma flow được nối đầy đủ.",
    createPost: "Tạo bài viết",
    titlePlaceholder: "Tiêu đề",
    bodyPlaceholder: "Chia sẻ mẹo, công thức hoặc ưu đãi...",
    post: "Đăng",
  },
  chat: {
    title: "Tin nhắn",
    subtitle: "Xem đoạn chat đơn hàng và xóa những đoạn cũ hơn.",
    orderRequestCreated: "Yêu cầu đơn hàng đã được tạo.",
    deliveryAddressShared: "Đã chia sẻ địa chỉ giao hàng",
    newUpdate: "Cập nhật mới",
    deleteConfirm: "Bạn có chắc muốn xóa đoạn chat này không?",
    noChatsYet: "Chưa có đoạn chat",
    noChatsDescription: "Sau khi gửi yêu cầu đơn hàng, nó sẽ hiện ở đây.",
    openChat: "Mở đoạn chat",
  },
  shop: {
    title: "Cửa hàng",
    subtitle: "Bấm vào bất kỳ mặt hàng nào để xem chi tiết đầy đủ.",
    searchPlaceholder: "Tìm theo tên, danh mục, mô tả, thẻ hoặc giá...",
    noProductsAvailable: "Chưa có sản phẩm nào.",
    noProductsMatch: "Không có sản phẩm phù hợp tìm kiếm.",
    itemDetails: "Chi tiết mặt hàng",
    addToCart: "Thêm vào giỏ",
    addsTo: "Thêm vào:",
    selectedCartFallback: "Giỏ hàng được chọn",
    createCartToStart: "Tạo giỏ hàng để bắt đầu thêm mặt hàng.",
    yourCarts: "Giỏ hàng của bạn",
    selectedCart: "Giỏ hàng được chọn",
    manageCartsSubtitle: "Mo mot gio de xem, hoac chon nhieu gio de xoa.",
    searchCartsPlaceholder: "Tìm giỏ hàng...",
    selectACart: "Chọn một giỏ hàng...",
    defaultCartName: "Giỏ hàng của tôi",
    cartName: "Tên giỏ hàng",
    noCartsYet: "Chưa có giỏ hàng nào.",
    noCartsMatch: "Không có giỏ hàng phù hợp.",
    openFullCart: "Mở toàn bộ giỏ hàng",
    cartItems: "Mặt hàng trong giỏ",
    chooseCartToView: "Chọn một giỏ hàng để xem mặt hàng.",
    noCartSelected: "Chưa chọn giỏ hàng.",
    cartIsEmpty: "Giỏ hàng này đang trống.",
    each: "mỗi cái",
    inCart: (qty: number) => `${qty} trong giỏ`,
    deleteCartTitle: "Xóa giỏ hàng",
    close: "Đóng",
    deleteCartConfirm: (name: string) => `Xóa "${name}" cùng toàn bộ mặt hàng bên trong?`,
    selectCartFirst: "Hãy chọn ít nhất một giỏ hàng trước.",
    confirmDeleteSelectedCarts: (count: number) =>
      `Xóa ${count} giỏ hàng đã chọn và toàn bộ mặt hàng bên trong?`,
    createOrSelectCartFirst:
      "Hãy tạo hoặc chọn một giỏ hàng trước ở bên phải rồi mới thêm mặt hàng.",
  },
  cartDetail: {
    title: "Giỏ hàng của bạn",
    subtitle: "Tìm sản phẩm, thêm vào giỏ và cập nhật số lượng.",
    addItems: "Thêm mặt hàng",
    searchProducts: "Tìm sản phẩm...",
    noMatches: "Không tìm thấy.",
    uncategorized: "Chưa phân loại",
    cartItems: "Mặt hàng trong giỏ",
    noItemsYet: "Chưa có mặt hàng nào. Tìm ở trên để thêm.",
    noPrice: "Không có giá",
    remove: "Bỏ",
    orderTotal: "Tổng đơn hàng",
    taxRate: "Thuế 9%",
    deliveryAddress: "Địa chỉ giao hàng",
    selectAddress: "Chọn địa chỉ...",
    noteToAdmin: "Ghi chú cho quản trị viên",
    notePlaceholder: "Ghi chú tùy chọn về giao hàng, đổi món hoặc thời gian...",
    sendingOrder: "Đang gửi đơn...",
    sendOrderRequest: "Gửi yêu cầu đơn hàng",
    cartEmptyAlert: "Giỏ hàng của bạn đang trống.",
    addressRequiredAlert: "Vui lòng thêm hoặc chọn địa chỉ giao hàng trước.",
    couldNotCreateOrder: "Không thể tạo đơn hàng.",
    addressOption: (label: string, street: string, city: string) => `${label} - ${street}, ${city}`,
  },
  profile: {
    title: "Hồ sơ",
    account: "Tài khoản",
    saveProfile: "Lưu hồ sơ",
    addAddress: "Thêm địa chỉ",
    labelPlaceholder: "Nhãn (Nhà, Công ty)",
    recipientNamePlaceholder: "Tên người nhận",
    phonePlaceholder: "Số điện thoại",
    streetPlaceholder: "Địa chỉ đường phố",
    apartmentPlaceholder: "Căn hộ / số phòng",
    cityPlaceholder: "Thành phố",
    statePlaceholder: "Tiểu bang",
    zipPlaceholder: "Mã ZIP",
    countryPlaceholder: "Quốc gia",
    deliveryNotesPlaceholder: "Ghi chú giao hàng",
    makeDefault: "Đặt địa chỉ này làm mặc định",
    addAddressButton: "Thêm địa chỉ",
    savedAddresses: "Địa chỉ đã lưu",
    noAddressesYet: "Chưa có địa chỉ nào.",
    profileSaved: "Đã lưu hồ sơ",
    cannotDeleteUsedAddress:
      "Không thể xóa địa chỉ này vì nó đã được sử dụng trong một hoặc nhiều đơn hàng. Hãy giữ lại cho lịch sử đơn hàng, hoặc thêm địa chỉ mới và đặt địa chỉ đó làm mặc định.",
    deleteAddressConfirm: "Xóa địa chỉ đã lưu này?",
    makeDefaultButton: "Đặt mặc định",
    defaultBadge: "Mặc định",
    addressFallback: "Địa chỉ",
    homeLabel: "Nhà",
  },
  orderDetail: {
    deleteConfirm: "Bạn có chắc muốn xóa đoạn chat này không?",
    orderSummary: "Tóm tắt đơn hàng",
    selectedDeliveryAddress: "Địa chỉ giao hàng đã chọn",
    orderChat: "Chat đơn hàng",
    adminDeletedTitle: "Đoạn chat này đã bị admin xóa.",
    adminDeletedBody: "Bạn vẫn có thể xem lại ở đây. Bạn có muốn xóa nó luôn không?",
    deleteThisChat: "Xóa đoạn chat này",
    addressChip: (label: string) => `Địa chỉ: ${label}`,
    sendAddressTitle: "Gửi địa chỉ này vào chat",
    typeMessage: "Nhập tin nhắn...",
    noMessagesYet: "Chưa có tin nhắn nào.",
  },
  admin: {
    dashboardTitle: "Bảng điều khiển admin",
    dashboardSubtitle: "Quản lý sản phẩm và đoạn chat đơn hàng thực tế của khách.",
    tabChat: "Chat",
    tabItems: "Sản phẩm",
    addProduct: "Thêm sản phẩm",
    productName: "Tên sản phẩm",
    productImage: "Hình sản phẩm",
    newProductImage: "Hình sản phẩm mới",
    priceUsd: "Giá (USD)",
    tags: "Thẻ",
    tagsPlaceholder: "Tươi, Hữu cơ, 1 lb",
    tagsHint: "Tách mỗi thuộc tính bằng dấu phẩy.",
    description: "Mô tả",
    descriptionPlaceholder: "Mô tả cho mặt hàng này",
    addProductButton: "Thêm sản phẩm",
    products: "Sản phẩm",
    searchItemsPlaceholder: "Tìm theo tên, thẻ, mô tả hoặc giá...",
    noProductsYet: "Chưa có sản phẩm nào.",
    noProductsMatch: "Không có sản phẩm phù hợp tìm kiếm.",
    productDescriptionPlaceholder: "Mô tả sản phẩm",
    pricePlaceholder: "Giá",
    edit: "Sửa",
    inStock: "Còn hàng",
    outOfStock: "Hết hàng",
    customerChats: "Chat khách hàng",
    customerChatsSubtitle:
      "Tìm theo tên khách hoặc đơn hàng, sau đó dùng bộ lọc theo ngày và tổng tiền.",
    select: "Chọn",
    markShipped: "Đánh dấu đã gửi",
    searchCustomersPlaceholder: "Tìm tên khách hoặc mã đơn #...",
    openFilters: "Mở bộ lọc",
    advancedFilters: "Bộ lọc nâng cao",
    fromDate: "Từ ngày",
    toDate: "Đến ngày",
    minTotal: "Tổng tối thiểu",
    maxTotal: "Tổng tối đa",
    noOrderChats: "Chưa có chat đơn hàng nào.",
    noChatsMatch: "Không có đoạn chat phù hợp bộ lọc hiện tại.",
    selectChatFirst: "Hãy chọn ít nhất một đoạn chat trước.",
    confirmMarkSelectedShipped:
      "Bạn có chắc muốn đánh dấu các đoạn chat đã chọn là đã gửi hàng không?",
    confirmHideSelectedChats:
      "Bạn có chắc muốn xóa các đoạn chat đã chọn khỏi bảng admin không?",
    adminNotFound: "Không tìm thấy admin đang đăng nhập.",
    confirmMarkCurrentShipped: "Bạn có chắc muốn đánh dấu đơn này là đã gửi hàng không?",
    imageUploadFailed: "Tải hình ảnh thất bại.",
    loadingChat: "Đang tải đoạn chat...",
    orderNotFound: "Không tìm thấy đơn hàng.",
    orderSummary: "Tóm tắt đơn hàng",
    hideDetails: "Ẩn chi tiết",
    showDetails: "Hiện chi tiết",
    showAddress: "Hiện địa chỉ",
    hideAddress: "Ẩn địa chỉ",
    noAddressShared: "Chưa có địa chỉ được chia sẻ.",
    noMessagesYet: "Chưa có tin nhắn nào.",
    typeReply: "Nhập phản hồi và nhấn Enter...",
  },
};

const es: AppCopy = {
  layout: {
    brandTagline: "Delicioso | Flexible | Facil",
    nav: {
      home: "Inicio",
      shop: "Tienda",
      community: "Comunidad",
      chat: "Chat",
    },
    signIn: "Iniciar sesion",
    profile: "Perfil",
    settings: "Ajustes",
    language: "Idioma",
    theme: "Modo",
    light: "Claro",
    dark: "Oscuro",
    languageNames: {
      en: "English",
      vi: "Tiếng Việt",
      es: "Español",
    },
    signOut: "Cerrar sesion",
    signOutFailed: "No se pudo cerrar sesion",
  },
  common: {
    save: "Guardar",
    cancel: "Cancelar",
    close: "Cerrar",
    open: "Abrir",
    show: "Mostrar",
    hide: "Ocultar",
    delete: "Eliminar",
    clear: "Limpiar",
    done: "Listo",
    add: "Agregar",
    send: "Enviar",
    loading: "Cargando...",
    loadingChat: "Cargando chat...",
    working: "Trabajando...",
    searching: "Buscando...",
    adding: "Agregando...",
    deleting: "Eliminando...",
    sending: "Enviando...",
    you: "Tu",
    admin: "Admin",
    email: "Correo",
    password: "Contrasena",
    phone: "Telefono",
    fullName: "Nombre completo",
    address: "Direccion",
    deliveryAddress: "Direccion de entrega",
    noRecipient: "Sin destinatario",
    notes: "Notas",
    subtotal: "Subtotal",
    tax: "Impuesto",
    shipping: "Envio",
    total: "Total",
    status: "Estado",
    placed: "Realizado",
    items: "Articulos",
    description: "Descripcion",
    properties: "Propiedades",
    emptyMessage: "Mensaje vacio",
    noImage: "Sin imagen",
    noImageAvailable: "No hay imagen disponible",
    noDescriptionYet: "Todavia no hay descripcion.",
    shownCount: (shown: number, total: number) => `${shown} / ${total} mostrados`,
    orderId: (id: string) => `Pedido #${id.slice(0, 8)}`,
    customerId: (id: string) => `Cliente ${id.slice(0, 8)}`,
    orderCreated: (count: number) => `Pedido creado con ${count} articulo(s).`,
    orderPreviewTotal: (total: string) => `Total del pedido ${total}`,
    notesValue: (notes: string) => `Notas: ${notes}`,
    phoneValue: (phone: string) => `Telefono: ${phone}`,
    deleteCartAria: (name: string) => `Eliminar ${name}`,
    removeItemAria: (name: string) => `Quitar ${name}`,
  },
  status: {
    pending: "Pendiente",
    confirmed: "Confirmado",
    shipped: "Enviado",
    out_for_delivery: "En reparto",
    packaging: "Packaging",
    delivered: "Entregado",
    cancelled: "Cancelado",
    archived: "Archive",
  },
  productImageField: {
    noImageSelected: "No hay imagen seleccionada",
    pasteImageUrl: "Pega aqui la URL de la imagen",
    uploading: "Subiendo...",
    uploadImage: "Subir imagen",
    clear: "Limpiar",
    helperText: "Pega una URL de imagen o sube un archivo a ImageKit.",
  },
  requireAdmin: {
    checking: "Verificando acceso de admin...",
  },
  home: {
    heroBadge: "Planificacion inteligente para las compras de cada dia",
    heroTitle: "Comprar comida se siente organizado, social y realmente util.",
    heroDescription:
      "Llena carritos, explora productos y comparte ideas con tu comunidad en una experiencia limpia. Menos friccion, menos olvidos y una mejor forma de planear comidas juntos.",
    startShopping: "Empezar a comprar",
    signInToStart: "Inicia sesion para empezar",
    exploreCommunity: "Explorar comunidad",
    statFastTitle: "Rapido",
    statFastDesc: "Carritos rapidos",
    statSimpleTitle: "Simple",
    statSimpleDesc: "Exploracion limpia",
    statSocialTitle: "Social",
    statSocialDesc: "Ideas de la comunidad",
    flowTitle: "Flujo de esta semana",
    flowDescription: "Una mejor experiencia de compra desde la planificacion hasta el pedido.",
    live: "En vivo",
    step1Title: "1. Descubre productos",
    step1Desc: "Explora una cuadricula clara y agrega productos en segundos.",
    step2Title: "2. Crea tu carrito",
    step2Desc: "Manten tu plan de compras organizado con carritos personales.",
    step3Title: "3. Aprende de la comunidad",
    step3Desc: "Comparte recetas, consejos y hallazgos locales con otros compradores.",
    cartsTitle: "Carritos",
    cartsDesc: "Listos para pedir",
    shopTitle: "Tienda",
    shopDesc: "Explora mas rapido",
    postsTitle: "Publicaciones",
    postsDesc: "Comparte ideas",
    card1Title: "Compras mas inteligentes",
    card1Desc: "Convierte notas sueltas en un carrito claro que realmente puedas usar.",
    card2Title: "Capa comunitaria",
    card2Desc: "Descubre recetas, recomendaciones e ideas de personas que compran como tu.",
    card3Title: "Listo para crecer",
    card3Desc:
      "Una base solida para ampliar la marca, categorias, promociones y mejor contenido de producto.",
  },
  auth: {
    signIn: "Iniciar sesion",
    createAccount: "Crear cuenta",
    signUp: "Registrarse",
    checkEmailMessage: "Revisa tu correo para confirmar tu cuenta y luego inicia sesion.",
    somethingWentWrong: "Algo salio mal",
    authSettingsNote:
      "Configuracion de Supabase Auth: activa el proveedor Email y define Site URL + Redirect URLs para Netlify.",
  },
  community: {
    title: "Comunidad",
    subtitle: "Publicaciones publicas. Agrega comentarios o me gusta cuando tu flujo de Figma este listo.",
    createPost: "Crear publicacion",
    titlePlaceholder: "Titulo",
    bodyPlaceholder: "Comparte un consejo, receta u oferta...",
    post: "Publicar",
  },
  chat: {
    title: "Chat",
    subtitle: "Revisa tus chats de pedidos y elimina los mas antiguos.",
    orderRequestCreated: "Solicitud de pedido creada.",
    deliveryAddressShared: "Direccion de entrega compartida",
    newUpdate: "Nueva actualizacion",
    deleteConfirm: "Seguro que quieres eliminar este chat?",
    noChatsYet: "Todavia no hay chats",
    noChatsDescription: "Cuando envies una solicitud de pedido, aparecera aqui.",
    openChat: "Abrir chat",
  },
  shop: {
    title: "Tienda",
    subtitle: "Haz clic en cualquier articulo para ver todos los detalles.",
    searchPlaceholder: "Busca por nombre, categoria, descripcion, etiqueta o precio...",
    noProductsAvailable: "Todavia no hay productos disponibles.",
    noProductsMatch: "No hay productos que coincidan con tu busqueda.",
    itemDetails: "Detalles del articulo",
    addToCart: "Agregar al carrito",
    addsTo: "Se agrega a:",
    selectedCartFallback: "Carrito seleccionado",
    createCartToStart: "Crea un carrito para empezar a agregar articulos.",
    yourCarts: "Tus carritos",
    selectedCart: "Carrito seleccionado",
    manageCartsSubtitle: "Abre un carrito para revisarlo o selecciona varios para eliminarlos.",
    searchCartsPlaceholder: "Buscar carritos...",
    selectACart: "Selecciona un carrito...",
    defaultCartName: "Mi carrito",
    cartName: "Nombre del carrito",
    noCartsYet: "Todavia no hay carritos.",
    noCartsMatch: "Ningun carrito coincide con tu busqueda.",
    openFullCart: "Abrir carrito completo",
    cartItems: "Articulos del carrito",
    chooseCartToView: "Elige un carrito para ver sus articulos.",
    noCartSelected: "No hay carrito seleccionado.",
    cartIsEmpty: "Este carrito esta vacio.",
    each: "cada uno",
    inCart: (qty: number) => `${qty} en el carrito`,
    deleteCartTitle: "Eliminar carrito",
    close: "Cerrar",
    deleteCartConfirm: (name: string) => `Eliminar "${name}" y todos sus articulos?`,
    selectCartFirst: "Selecciona al menos un carrito primero.",
    confirmDeleteSelectedCarts: (count: number) =>
      `Eliminar ${count} carrito(s) seleccionados y todos sus articulos?`,
    createOrSelectCartFirst:
      "Crea o selecciona primero un carrito en el panel derecho antes de agregar articulos.",
  },
  cartDetail: {
    title: "Tu carrito",
    subtitle: "Busca productos, agrega articulos y actualiza cantidades.",
    addItems: "Agregar articulos",
    searchProducts: "Buscar productos...",
    noMatches: "Sin resultados.",
    uncategorized: "Sin categoria",
    cartItems: "Articulos del carrito",
    noItemsYet: "Todavia no hay articulos. Busca arriba para agregar.",
    noPrice: "Sin precio",
    remove: "Quitar",
    orderTotal: "Total del pedido",
    taxRate: "Impuesto 9%",
    deliveryAddress: "Direccion de entrega",
    selectAddress: "Selecciona direccion...",
    noteToAdmin: "Nota para admin",
    notePlaceholder: "Nota opcional sobre entrega, sustituciones o tiempo...",
    sendingOrder: "Enviando pedido...",
    sendOrderRequest: "Enviar solicitud de pedido",
    cartEmptyAlert: "Tu carrito esta vacio.",
    addressRequiredAlert: "Agrega o selecciona primero una direccion de entrega.",
    couldNotCreateOrder: "No se pudo crear el pedido.",
    addressOption: (label: string, street: string, city: string) => `${label} - ${street}, ${city}`,
  },
  profile: {
    title: "Perfil",
    account: "Cuenta",
    saveProfile: "Guardar perfil",
    addAddress: "Agregar direccion",
    labelPlaceholder: "Etiqueta (Casa, Trabajo)",
    recipientNamePlaceholder: "Nombre del destinatario",
    phonePlaceholder: "Telefono",
    streetPlaceholder: "Direccion",
    apartmentPlaceholder: "Apartamento / unidad",
    cityPlaceholder: "Ciudad",
    statePlaceholder: "Estado",
    zipPlaceholder: "Codigo postal",
    countryPlaceholder: "Pais",
    deliveryNotesPlaceholder: "Notas de entrega",
    makeDefault: "Hacer esta mi direccion predeterminada",
    addAddressButton: "Agregar direccion",
    savedAddresses: "Direcciones guardadas",
    noAddressesYet: "Todavia no hay direcciones.",
    profileSaved: "Perfil guardado",
    cannotDeleteUsedAddress:
      "No puedes eliminar esta direccion porque ya se usa en uno o mas pedidos. Conservala para el historial o agrega una nueva y ponla como predeterminada.",
    deleteAddressConfirm: "Eliminar esta direccion guardada?",
    makeDefaultButton: "Hacer predeterminada",
    defaultBadge: "Predeterminada",
    addressFallback: "Direccion",
    homeLabel: "Casa",
  },
  orderDetail: {
    deleteConfirm: "Seguro que quieres eliminar este chat?",
    orderSummary: "Resumen del pedido",
    selectedDeliveryAddress: "Direccion de entrega seleccionada",
    orderChat: "Chat del pedido",
    adminDeletedTitle: "Este chat fue eliminado por admin.",
    adminDeletedBody: "Aun puedes revisarlo aqui. Quieres eliminarlo tambien?",
    deleteThisChat: "Eliminar este chat",
    addressChip: (label: string) => `Direccion: ${label}`,
    sendAddressTitle: "Enviar esta direccion al chat",
    typeMessage: "Escribe un mensaje...",
    noMessagesYet: "Todavia no hay mensajes.",
  },
  admin: {
    dashboardTitle: "Panel de admin",
    dashboardSubtitle: "Gestiona productos y chats reales de pedidos de clientes.",
    tabChat: "Chat",
    tabItems: "Articulos",
    addProduct: "Agregar producto",
    productName: "Nombre del producto",
    productImage: "Imagen del producto",
    newProductImage: "Imagen de producto nueva",
    priceUsd: "Precio (USD)",
    tags: "Etiquetas",
    tagsPlaceholder: "Fresco, Organico, 1 lb",
    tagsHint: "Separa cada propiedad con una coma.",
    description: "Descripcion",
    descriptionPlaceholder: "Una descripcion para este articulo",
    addProductButton: "Agregar producto",
    products: "Productos",
    searchItemsPlaceholder: "Buscar por nombre, etiqueta, descripcion o precio...",
    noProductsYet: "Todavia no hay productos.",
    noProductsMatch: "No hay productos que coincidan con tu busqueda.",
    productDescriptionPlaceholder: "Descripcion del producto",
    pricePlaceholder: "Precio",
    edit: "Editar",
    inStock: "En stock",
    outOfStock: "Agotado",
    customerChats: "Chats de clientes",
    customerChatsSubtitle:
      "Busca por nombre del cliente o pedido y luego usa filtros por fecha y total.",
    select: "Seleccionar",
    markShipped: "Marcar entregado",
    searchCustomersPlaceholder: "Buscar nombre del cliente o pedido #...",
    openFilters: "Abrir filtros",
    advancedFilters: "Filtros avanzados",
    fromDate: "Desde",
    toDate: "Hasta",
    minTotal: "Total minimo",
    maxTotal: "Total maximo",
    noOrderChats: "Todavia no hay chats de pedidos.",
    noChatsMatch: "Ningun chat coincide con los filtros actuales.",
    selectChatFirst: "Selecciona al menos un chat primero.",
    confirmMarkSelectedShipped:
      "Seguro que quieres marcar los chats seleccionados como entregados?",
    confirmHideSelectedChats:
      "Seguro que quieres quitar los chats seleccionados solo del panel de admin?",
    adminNotFound: "No se pudo encontrar al admin conectado.",
    confirmMarkCurrentShipped: "Seguro que quieres marcar este pedido como entregado?",
    imageUploadFailed: "Fallo la subida de imagen.",
    loadingChat: "Cargando chat...",
    orderNotFound: "Pedido no encontrado.",
    orderSummary: "Resumen del pedido",
    hideDetails: "Ocultar detalles",
    showDetails: "Mostrar detalles",
    showAddress: "Mostrar direccion",
    hideAddress: "Ocultar direccion",
    noAddressShared: "Todavia no se compartio direccion.",
    noMessagesYet: "Todavia no hay mensajes.",
    typeReply: "Escribe una respuesta y presiona Enter...",
  },
};

const copyByLanguage: Record<Language, AppCopy> = {
  en,
  vi,
  es,
};

const localeByLanguage: Record<Language, string> = {
  en: "en-US",
  vi: "vi-VN",
  es: "es-ES",
};

function getSavedLanguage(): Language {
  if (typeof window === "undefined") return "en";
  const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return saved === "vi" || saved === "es" ? saved : "en";
}

function getSavedTheme(): ThemeMode {
  if (typeof window === "undefined") return "light";
  const saved = window.localStorage.getItem(THEME_STORAGE_KEY);
  if (saved === "dark" || saved === "light") return saved;
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

function parseOrderCreatedCount(body: string | null) {
  if (!body) return null;

  const normalized = body.trim();
  const tokenMatch = normalized.match(/^order_created:(\d+)$/i);
  if (tokenMatch) return Number(tokenMatch[1]);

  const legacyPatterns = [
    /^Order created with (\d+) item\(s\)\.?$/i,
    /^Don hang duoc tao voi (\d+) mat hang\.?$/i,
    /^Đơn hàng được tạo với (\d+) mặt hàng\.?$/i,
    /^Pedido creado con (\d+) articulo\(s\)\.?$/i,
  ];

  for (const pattern of legacyPatterns) {
    const match = normalized.match(pattern);
    if (match) return Number(match[1]);
  }

  return null;
}

type AppSettingsContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  theme: ThemeMode;
  setTheme: (theme: ThemeMode) => void;
  copy: AppCopy;
  locale: string;
  formatCurrency: (cents: number) => string;
  formatDateTime: (value: string | number | Date) => string;
  formatStatus: (status: string) => string;
  formatStoredMessage: (messageType: string, body: string | null) => string;
};

const AppSettingsContext = createContext<AppSettingsContextValue | null>(null);

export function AppSettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(getSavedLanguage);
  const [theme, setTheme] = useState<ThemeMode>(getSavedTheme);

  const copy = copyByLanguage[language];
  const locale = localeByLanguage[language];

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  useLayoutEffect(() => {
    window.localStorage.setItem(THEME_STORAGE_KEY, theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo<AppSettingsContextValue>(() => {
    const currencyFormatter = new Intl.NumberFormat(locale, {
      style: "currency",
      currency: "USD",
    });
    const dateTimeFormatter = new Intl.DateTimeFormat(locale, {
      dateStyle: "medium",
      timeStyle: "short",
    });

    return {
      language,
      setLanguage,
      theme,
      setTheme,
      copy,
      locale,
      formatCurrency: (cents: number) => currencyFormatter.format(cents / 100),
      formatDateTime: (value: string | number | Date) =>
        dateTimeFormatter.format(new Date(value)),
      formatStatus: (status: string) =>
        copy.status[status as keyof AppCopy["status"]] ?? status,
      formatStoredMessage: (messageType: string, body: string | null) => {
        if (messageType === "system") {
          const count = parseOrderCreatedCount(body);
          if (count !== null) return copy.common.orderCreated(count);
        }

        return body?.trim() || copy.common.emptyMessage;
      },
    };
  }, [copy, language, locale, theme]);

  return <AppSettingsContext.Provider value={value}>{children}</AppSettingsContext.Provider>;
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error("useAppSettings must be used within AppSettingsProvider");
  }
  return context;
}
