import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from "react";

export type Language = "en" | "vi" | "es";
export type ThemeMode = "light" | "dark";

const LANGUAGE_STORAGE_KEY = "tenshop-language";
const THEME_STORAGE_KEY = "tenshop-theme";

const en = {
  layout: {
    brandTagline: "Delicious | Flexible | Easy",
    nav: {
      home: "Home",
      shop: "Shop",
      community: "Community",
      chat: "Chat",
    },
    signIn: "Sign in",
    profile: "Profile",
    settings: "Settings",
    language: "Language",
    theme: "Mode",
    light: "Light",
    dark: "Dark",
    languageNames: {
      en: "English",
      vi: "Tieng Viet",
      es: "Espanol",
    },
    signOut: "Sign out",
    signOutFailed: "Sign out failed",
  },
  common: {
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    open: "Open",
    show: "Show",
    hide: "Hide",
    delete: "Delete",
    clear: "Clear",
    done: "Done",
    add: "Add",
    send: "Send",
    loading: "Loading...",
    loadingChat: "Loading chat...",
    working: "Working...",
    searching: "Searching...",
    adding: "Adding...",
    deleting: "Deleting...",
    sending: "Sending...",
    you: "You",
    admin: "Admin",
    email: "Email",
    password: "Password",
    phone: "Phone",
    fullName: "Full name",
    address: "Address",
    deliveryAddress: "Delivery address",
    noRecipient: "No recipient",
    notes: "Notes",
    subtotal: "Subtotal",
    tax: "Tax",
    shipping: "Shipping",
    total: "Total",
    status: "Status",
    placed: "Placed",
    items: "Items",
    description: "Description",
    properties: "Properties",
    emptyMessage: "Empty message",
    noImage: "No image",
    noImageAvailable: "No image available",
    noDescriptionYet: "No description added yet.",
    shownCount: (shown: number, total: number) => `${shown} / ${total} shown`,
    orderId: (id: string) => `Order #${id.slice(0, 8)}`,
    customerId: (id: string) => `Customer ${id.slice(0, 8)}`,
    orderCreated: (count: number) => `Order created with ${count} item(s).`,
    orderPreviewTotal: (total: string) => `Order total ${total}`,
    notesValue: (notes: string) => `Notes: ${notes}`,
    phoneValue: (phone: string) => `Phone: ${phone}`,
    deleteListAria: (name: string) => `Delete ${name}`,
    removeItemAria: (name: string) => `Remove ${name}`,
  },
  status: {
    pending: "Pending",
    confirmed: "Confirmed",
    shipped: "Shipped",
    out_for_delivery: "Out for delivery",
    delivered: "Delivered",
    cancelled: "Cancelled",
  },
  productImageField: {
    noImageSelected: "No image selected",
    pasteImageUrl: "Paste image URL here",
    uploading: "Uploading...",
    uploadImage: "Upload image",
    clear: "Clear",
    helperText: "Paste an image URL or upload a file to ImageKit.",
  },
  requireAdmin: {
    checking: "Checking admin...",
  },
  home: {
    heroBadge: "Smart grocery planning for everyday life",
    heroTitle: "Grocery shopping that feels organized, social, and actually useful.",
    heroDescription:
      "Build shopping lists, browse products, and share ideas with your community in one clean experience. Less friction, fewer forgotten items, and a better way to plan meals together.",
    startShopping: "Start Shopping",
    signInToStart: "Sign in to Start",
    exploreCommunity: "Explore Community",
    statFastTitle: "Fast",
    statFastDesc: "Quick list building",
    statSimpleTitle: "Simple",
    statSimpleDesc: "Clean product browsing",
    statSocialTitle: "Social",
    statSocialDesc: "Community-driven ideas",
    flowTitle: "This week's flow",
    flowDescription: "A better shopping experience from planning to checkout.",
    live: "Live",
    step1Title: "1. Discover products",
    step1Desc: "Browse a clean product grid and add items in seconds.",
    step2Title: "2. Build your list",
    step2Desc: "Keep your grocery plan organized with personal shopping lists.",
    step3Title: "3. Learn from community",
    step3Desc: "Share recipes, tips, and local finds with other shoppers.",
    listsTitle: "Lists",
    listsDesc: "Stay organized",
    shopTitle: "Shop",
    shopDesc: "Browse faster",
    postsTitle: "Posts",
    postsDesc: "Share ideas",
    card1Title: "Smarter shopping",
    card1Desc: "Turn scattered grocery notes into a clear list you can actually use.",
    card2Title: "Community layer",
    card2Desc: "Discover recipes, recommendations, and ideas from people shopping like you.",
    card3Title: "Ready to grow",
    card3Desc:
      "A strong base for richer branding, categories, promotions, and real product storytelling.",
  },
  auth: {
    signIn: "Sign in",
    createAccount: "Create account",
    signUp: "Sign up",
    checkEmailMessage: "Check your email to confirm your account, then sign in.",
    somethingWentWrong: "Something went wrong",
    authSettingsNote:
      "Supabase Auth settings: enable Email provider and set Site URL + Redirect URLs for Netlify.",
  },
  community: {
    title: "Community",
    subtitle: "Public posts. Add comments or likes once your Figma flow is wired.",
    createPost: "Create post",
    titlePlaceholder: "Title",
    bodyPlaceholder: "Share a tip, recipe, or deal...",
    post: "Post",
  },
  chat: {
    title: "Chat",
    subtitle: "View your order chats and delete older ones.",
    orderRequestCreated: "Order request created.",
    deliveryAddressShared: "Delivery address shared",
    newUpdate: "New update",
    deleteConfirm: "Are you sure you want to delete this chat?",
    noChatsYet: "No chats yet",
    noChatsDescription: "Once you send an order request, it will appear here.",
    openChat: "Open chat",
  },
  shop: {
    title: "Shop",
    subtitle: "Click any item to view full details.",
    searchPlaceholder: "Search items by name, category, description, tag, or price...",
    noProductsAvailable: "No products available yet.",
    noProductsMatch: "No products match your search.",
    itemDetails: "Item details",
    addToCart: "Add to cart",
    addsTo: "Adds to:",
    selectedListFallback: "Selected list",
    createListToStart: "Create a list to start adding items.",
    yourLists: "Your lists",
    selectedList: "Selected list",
    selectAList: "Select a list...",
    defaultListName: "My List",
    listName: "List name",
    noListsYet: "No lists yet.",
    openFullList: "Open full list",
    listItems: "List items",
    chooseListToView: "Choose a list to view its items.",
    noListSelected: "No list selected.",
    listIsEmpty: "This list is empty.",
    each: "each",
    inList: (qty: number) => `${qty} in list`,
    deleteListTitle: "Delete list",
    close: "Close",
    deleteListConfirm: (name: string) => `Delete "${name}" and all of its items?`,
    createOrSelectListFirst:
      "Create or select a list first in the right panel before adding items.",
  },
  listDetail: {
    title: "Your list",
    subtitle: "Search products, add to cart, and update quantities.",
    addItems: "Add items",
    searchProducts: "Search products...",
    noMatches: "No matches.",
    uncategorized: "Uncategorized",
    cartItems: "Cart items",
    noItemsYet: "No items yet. Search above to add.",
    noPrice: "No price",
    remove: "Remove",
    orderTotal: "Order total",
    taxRate: "Tax 9%",
    deliveryAddress: "Delivery address",
    selectAddress: "Select address...",
    noteToAdmin: "Note to admin",
    notePlaceholder: "Optional note about delivery, substitutions, timing...",
    sendingOrder: "Sending order...",
    sendOrderRequest: "Send order request",
    listEmptyAlert: "Your list is empty.",
    addressRequiredAlert: "Please add or select a delivery address first.",
    couldNotCreateOrder: "Could not create order.",
    addressOption: (label: string, street: string, city: string) => `${label} - ${street}, ${city}`,
  },
  profile: {
    title: "Profile",
    account: "Account",
    saveProfile: "Save profile",
    addAddress: "Add address",
    labelPlaceholder: "Label (Home, Work)",
    recipientNamePlaceholder: "Recipient name",
    phonePlaceholder: "Phone",
    streetPlaceholder: "Street address",
    apartmentPlaceholder: "Apartment / unit",
    cityPlaceholder: "City",
    statePlaceholder: "State",
    zipPlaceholder: "ZIP code",
    countryPlaceholder: "Country",
    deliveryNotesPlaceholder: "Delivery notes",
    makeDefault: "Make this my default address",
    addAddressButton: "Add address",
    savedAddresses: "Saved addresses",
    noAddressesYet: "No addresses yet.",
    profileSaved: "Profile saved",
    cannotDeleteUsedAddress:
      "You cannot delete this address because it is already used by one or more orders. Please keep it for order history, or add a new address and set that one as default.",
    deleteAddressConfirm: "Delete this saved address?",
    makeDefaultButton: "Make default",
    defaultBadge: "Default",
    addressFallback: "Address",
    homeLabel: "Home",
  },
  orderDetail: {
    deleteConfirm: "Are you sure you want to delete this chat?",
    orderSummary: "Order summary",
    selectedDeliveryAddress: "Selected delivery address",
    orderChat: "Order chat",
    adminDeletedTitle: "This chat was deleted by admin.",
    adminDeletedBody: "You can still review it here. Do you want to delete it too?",
    deleteThisChat: "Delete this chat",
    addressChip: (label: string) => `Address: ${label}`,
    sendAddressTitle: "Send this address into chat",
    typeMessage: "Type a message...",
    noMessagesYet: "No messages yet.",
  },
  admin: {
    dashboardTitle: "Admin Dashboard",
    dashboardSubtitle: "Manage products and real customer order chats.",
    tabChat: "Chat",
    tabItems: "Items",
    addProduct: "Add product",
    productName: "Product name",
    productImage: "Product image",
    newProductImage: "New product image",
    priceUsd: "Price (USD)",
    tags: "Tags",
    tagsPlaceholder: "Fresh, Organic, 1 lb",
    tagsHint: "Separate each property with a comma.",
    description: "Description",
    descriptionPlaceholder: "One description for this item",
    addProductButton: "Add Product",
    products: "Products",
    searchItemsPlaceholder: "Search items by name, tag, description, or price...",
    noProductsYet: "No products yet.",
    noProductsMatch: "No products match your search.",
    productDescriptionPlaceholder: "Product description",
    pricePlaceholder: "Price",
    edit: "Edit",
    inStock: "In stock",
    outOfStock: "Out of stock",
    customerChats: "Customer Chats",
    customerChatsSubtitle:
      "Search by customer name or order, then use filters for date and total.",
    select: "Select",
    markShipped: "Mark shipped",
    searchCustomersPlaceholder: "Search customer name or order #...",
    openFilters: "Open filters",
    advancedFilters: "Advanced Filters",
    fromDate: "From date",
    toDate: "To date",
    minTotal: "Min total",
    maxTotal: "Max total",
    noOrderChats: "No order chats yet.",
    noChatsMatch: "No chats match the current filters.",
    selectChatFirst: "Select at least one chat first.",
    confirmMarkSelectedShipped:
      "Are you sure you want to mark the selected chats as shipped?",
    confirmHideSelectedChats:
      "Are you sure you want to remove the selected chats from the admin board only?",
    adminNotFound: "Could not find the signed-in admin.",
    confirmMarkCurrentShipped: "Are you sure you want to mark this order as shipped?",
    imageUploadFailed: "Image upload failed.",
    loadingChat: "Loading chat...",
    orderNotFound: "Order not found.",
    orderSummary: "Order summary",
    hideDetails: "Hide details",
    showDetails: "Show details",
    showAddress: "Show address",
    hideAddress: "Hide address",
    noAddressShared: "No address shared yet.",
    noMessagesYet: "No messages yet.",
    typeReply: "Type a reply and press Enter...",
  },
};

type AppCopy = typeof en;

const vi: AppCopy = {
  layout: {
    brandTagline: "Ngon | Linh hoat | De dang",
    nav: {
      home: "Trang chu",
      shop: "Cua hang",
      community: "Cong dong",
      chat: "Tin nhan",
    },
    signIn: "Dang nhap",
    profile: "Ho so",
    settings: "Cai dat",
    language: "Ngon ngu",
    theme: "Giao dien",
    light: "Sang",
    dark: "Toi",
    languageNames: {
      en: "English",
      vi: "Tieng Viet",
      es: "Espanol",
    },
    signOut: "Dang xuat",
    signOutFailed: "Dang xuat that bai",
  },
  common: {
    save: "Luu",
    cancel: "Huy",
    close: "Dong",
    open: "Mo",
    show: "Hien",
    hide: "An",
    delete: "Xoa",
    clear: "Xoa bo loc",
    done: "Xong",
    add: "Them",
    send: "Gui",
    loading: "Dang tai...",
    loadingChat: "Dang tai doan chat...",
    working: "Dang xu ly...",
    searching: "Dang tim...",
    adding: "Dang them...",
    deleting: "Dang xoa...",
    sending: "Dang gui...",
    you: "Ban",
    admin: "Quan tri vien",
    email: "Email",
    password: "Mat khau",
    phone: "So dien thoai",
    fullName: "Ho ten",
    address: "Dia chi",
    deliveryAddress: "Dia chi giao hang",
    noRecipient: "Chua co nguoi nhan",
    notes: "Ghi chu",
    subtotal: "Tam tinh",
    tax: "Thue",
    shipping: "Phi giao hang",
    total: "Tong cong",
    status: "Trang thai",
    placed: "Dat luc",
    items: "Mat hang",
    description: "Mo ta",
    properties: "Thuoc tinh",
    emptyMessage: "Tin nhan rong",
    noImage: "Khong co hinh",
    noImageAvailable: "Chua co hinh anh",
    noDescriptionYet: "Chua co mo ta.",
    shownCount: (shown: number, total: number) => `${shown} / ${total} dang hien`,
    orderId: (id: string) => `Don #${id.slice(0, 8)}`,
    customerId: (id: string) => `Khach ${id.slice(0, 8)}`,
    orderCreated: (count: number) => `Don hang duoc tao voi ${count} mat hang.`,
    orderPreviewTotal: (total: string) => `Tong don ${total}`,
    notesValue: (notes: string) => `Ghi chu: ${notes}`,
    phoneValue: (phone: string) => `Dien thoai: ${phone}`,
    deleteListAria: (name: string) => `Xoa ${name}`,
    removeItemAria: (name: string) => `Bo ${name}`,
  },
  status: {
    pending: "Cho xu ly",
    confirmed: "Da xac nhan",
    shipped: "Da gui hang",
    out_for_delivery: "Dang giao",
    delivered: "Da giao",
    cancelled: "Da huy",
  },
  productImageField: {
    noImageSelected: "Chua chon hinh",
    pasteImageUrl: "Dan URL hinh anh vao day",
    uploading: "Dang tai len...",
    uploadImage: "Tai hinh anh",
    clear: "Xoa",
    helperText: "Dan URL hinh anh hoac tai tep len ImageKit.",
  },
  requireAdmin: {
    checking: "Dang kiem tra quyen quan tri...",
  },
  home: {
    heroBadge: "Lap ke hoach di cho thong minh moi ngay",
    heroTitle: "Di cho duoc sap xep gon gang, co tinh ket noi va that su huu ich.",
    heroDescription:
      "Tao danh sach mua sam, xem san pham va chia se y tuong voi cong dong trong mot trai nghiem gon gang. Giam boi roi, it quen do hon va de cung nhau len ke hoach bua an.",
    startShopping: "Bat dau mua sam",
    signInToStart: "Dang nhap de bat dau",
    exploreCommunity: "Kham pha cong dong",
    statFastTitle: "Nhanh",
    statFastDesc: "Tao danh sach nhanh",
    statSimpleTitle: "Don gian",
    statSimpleDesc: "Xem san pham gon gang",
    statSocialTitle: "Cong dong",
    statSocialDesc: "Y tuong tu moi nguoi",
    flowTitle: "Quy trinh tuan nay",
    flowDescription: "Trai nghiem mua sam tot hon tu luc lap ke hoach den khi dat hang.",
    live: "Dang hoat dong",
    step1Title: "1. Kham pha san pham",
    step1Desc: "Xem luoi san pham gon gang va them mat hang trong vai giay.",
    step2Title: "2. Tao danh sach",
    step2Desc: "Giu ke hoach di cho gon gang voi danh sach ca nhan.",
    step3Title: "3. Hoc tu cong dong",
    step3Desc: "Chia se cong thuc, meo va mon hay voi nguoi mua sam khac.",
    listsTitle: "Danh sach",
    listsDesc: "Sap xep de dang",
    shopTitle: "Mua sam",
    shopDesc: "Xem nhanh hon",
    postsTitle: "Bai viet",
    postsDesc: "Chia se y tuong",
    card1Title: "Mua sam thong minh hon",
    card1Desc: "Bien ghi chu mua sam roi rac thanh danh sach ro rang de su dung.",
    card2Title: "Lop cong dong",
    card2Desc: "Tim cong thuc, goi y va y tuong tu nhung nguoi mua sam giong ban.",
    card3Title: "San sang phat trien",
    card3Desc:
      "Nen tang tot de mo rong thuong hieu, danh muc, khuyen mai va noi dung san pham sau nay.",
  },
  auth: {
    signIn: "Dang nhap",
    createAccount: "Tao tai khoan",
    signUp: "Dang ky",
    checkEmailMessage: "Kiem tra email de xac nhan tai khoan, sau do dang nhap.",
    somethingWentWrong: "Da co loi xay ra",
    authSettingsNote:
      "Cai dat Supabase Auth: bat Email provider va dat Site URL + Redirect URLs cho Netlify.",
  },
  community: {
    title: "Cong dong",
    subtitle: "Bai viet cong khai. Co the them binh luan hoac thich sau khi Figma flow duoc noi day du.",
    createPost: "Tao bai viet",
    titlePlaceholder: "Tieu de",
    bodyPlaceholder: "Chia se meo, cong thuc hoac uu dai...",
    post: "Dang bai",
  },
  chat: {
    title: "Tin nhan",
    subtitle: "Xem doan chat don hang va xoa nhung doan cu hon.",
    orderRequestCreated: "Yeu cau don hang da duoc tao.",
    deliveryAddressShared: "Da chia se dia chi giao hang",
    newUpdate: "Cap nhat moi",
    deleteConfirm: "Ban co chac muon xoa doan chat nay khong?",
    noChatsYet: "Chua co doan chat",
    noChatsDescription: "Sau khi gui yeu cau don hang, no se hien o day.",
    openChat: "Mo doan chat",
  },
  shop: {
    title: "Cua hang",
    subtitle: "Bam vao bat ky mat hang nao de xem chi tiet day du.",
    searchPlaceholder: "Tim theo ten, danh muc, mo ta, the hoac gia...",
    noProductsAvailable: "Chua co san pham nao.",
    noProductsMatch: "Khong co san pham phu hop tim kiem.",
    itemDetails: "Chi tiet mat hang",
    addToCart: "Them vao gio",
    addsTo: "Them vao:",
    selectedListFallback: "Danh sach duoc chon",
    createListToStart: "Tao danh sach de bat dau them mat hang.",
    yourLists: "Danh sach cua ban",
    selectedList: "Danh sach duoc chon",
    selectAList: "Chon mot danh sach...",
    defaultListName: "Danh sach cua toi",
    listName: "Ten danh sach",
    noListsYet: "Chua co danh sach nao.",
    openFullList: "Mo danh sach day du",
    listItems: "Mat hang trong danh sach",
    chooseListToView: "Chon mot danh sach de xem mat hang.",
    noListSelected: "Chua chon danh sach.",
    listIsEmpty: "Danh sach nay dang trong.",
    each: "moi cai",
    inList: (qty: number) => `${qty} trong danh sach`,
    deleteListTitle: "Xoa danh sach",
    close: "Dong",
    deleteListConfirm: (name: string) => `Xoa "${name}" cung toan bo mat hang ben trong?`,
    createOrSelectListFirst:
      "Hay tao hoac chon mot danh sach truoc o ben phai roi moi them mat hang.",
  },
  listDetail: {
    title: "Danh sach cua ban",
    subtitle: "Tim san pham, them vao gio va cap nhat so luong.",
    addItems: "Them mat hang",
    searchProducts: "Tim san pham...",
    noMatches: "Khong tim thay.",
    uncategorized: "Chua phan loai",
    cartItems: "Mat hang trong gio",
    noItemsYet: "Chua co mat hang nao. Tim o tren de them.",
    noPrice: "Khong co gia",
    remove: "Bo",
    orderTotal: "Tong don hang",
    taxRate: "Thue 9%",
    deliveryAddress: "Dia chi giao hang",
    selectAddress: "Chon dia chi...",
    noteToAdmin: "Ghi chu cho quan tri vien",
    notePlaceholder: "Ghi chu tuy chon ve giao hang, doi mon hoac thoi gian...",
    sendingOrder: "Dang gui don...",
    sendOrderRequest: "Gui yeu cau don hang",
    listEmptyAlert: "Danh sach cua ban dang trong.",
    addressRequiredAlert: "Vui long them hoac chon dia chi giao hang truoc.",
    couldNotCreateOrder: "Khong the tao don hang.",
    addressOption: (label: string, street: string, city: string) => `${label} - ${street}, ${city}`,
  },
  profile: {
    title: "Ho so",
    account: "Tai khoan",
    saveProfile: "Luu ho so",
    addAddress: "Them dia chi",
    labelPlaceholder: "Nhan (Nha, Cong ty)",
    recipientNamePlaceholder: "Ten nguoi nhan",
    phonePlaceholder: "So dien thoai",
    streetPlaceholder: "Dia chi duong pho",
    apartmentPlaceholder: "Can ho / so phong",
    cityPlaceholder: "Thanh pho",
    statePlaceholder: "Tieu bang",
    zipPlaceholder: "Ma ZIP",
    countryPlaceholder: "Quoc gia",
    deliveryNotesPlaceholder: "Ghi chu giao hang",
    makeDefault: "Dat dia chi nay lam mac dinh",
    addAddressButton: "Them dia chi",
    savedAddresses: "Dia chi da luu",
    noAddressesYet: "Chua co dia chi nao.",
    profileSaved: "Da luu ho so",
    cannotDeleteUsedAddress:
      "Khong the xoa dia chi nay vi no da duoc su dung trong mot hoac nhieu don hang. Hay giu lai cho lich su don hang, hoac them dia chi moi va dat dia chi do lam mac dinh.",
    deleteAddressConfirm: "Xoa dia chi da luu nay?",
    makeDefaultButton: "Dat mac dinh",
    defaultBadge: "Mac dinh",
    addressFallback: "Dia chi",
    homeLabel: "Nha",
  },
  orderDetail: {
    deleteConfirm: "Ban co chac muon xoa doan chat nay khong?",
    orderSummary: "Tom tat don hang",
    selectedDeliveryAddress: "Dia chi giao hang da chon",
    orderChat: "Chat don hang",
    adminDeletedTitle: "Doan chat nay da bi admin xoa.",
    adminDeletedBody: "Ban van co the xem lai o day. Ban co muon xoa no luon khong?",
    deleteThisChat: "Xoa doan chat nay",
    addressChip: (label: string) => `Dia chi: ${label}`,
    sendAddressTitle: "Gui dia chi nay vao chat",
    typeMessage: "Nhap tin nhan...",
    noMessagesYet: "Chua co tin nhan nao.",
  },
  admin: {
    dashboardTitle: "Bang dieu khien admin",
    dashboardSubtitle: "Quan ly san pham va doan chat don hang thuc te cua khach.",
    tabChat: "Chat",
    tabItems: "San pham",
    addProduct: "Them san pham",
    productName: "Ten san pham",
    productImage: "Hinh san pham",
    newProductImage: "Hinh san pham moi",
    priceUsd: "Gia (USD)",
    tags: "The",
    tagsPlaceholder: "Tuoi, Huu co, 1 lb",
    tagsHint: "Tach moi thuoc tinh bang dau phay.",
    description: "Mo ta",
    descriptionPlaceholder: "Mo ta cho mat hang nay",
    addProductButton: "Them san pham",
    products: "San pham",
    searchItemsPlaceholder: "Tim theo ten, the, mo ta hoac gia...",
    noProductsYet: "Chua co san pham nao.",
    noProductsMatch: "Khong co san pham phu hop tim kiem.",
    productDescriptionPlaceholder: "Mo ta san pham",
    pricePlaceholder: "Gia",
    edit: "Sua",
    inStock: "Con hang",
    outOfStock: "Het hang",
    customerChats: "Chat khach hang",
    customerChatsSubtitle:
      "Tim theo ten khach hoac don hang, sau do dung bo loc theo ngay va tong tien.",
    select: "Chon",
    markShipped: "Danh dau da gui",
    searchCustomersPlaceholder: "Tim ten khach hoac ma don #...",
    openFilters: "Mo bo loc",
    advancedFilters: "Bo loc nang cao",
    fromDate: "Tu ngay",
    toDate: "Den ngay",
    minTotal: "Tong toi thieu",
    maxTotal: "Tong toi da",
    noOrderChats: "Chua co chat don hang nao.",
    noChatsMatch: "Khong co doan chat phu hop bo loc hien tai.",
    selectChatFirst: "Hay chon it nhat mot doan chat truoc.",
    confirmMarkSelectedShipped:
      "Ban co chac muon danh dau cac doan chat da chon la da gui hang khong?",
    confirmHideSelectedChats:
      "Ban co chac muon xoa cac doan chat da chon khoi bang admin khong?",
    adminNotFound: "Khong tim thay admin dang dang nhap.",
    confirmMarkCurrentShipped: "Ban co chac muon danh dau don nay la da gui hang khong?",
    imageUploadFailed: "Tai hinh anh that bai.",
    loadingChat: "Dang tai doan chat...",
    orderNotFound: "Khong tim thay don hang.",
    orderSummary: "Tom tat don hang",
    hideDetails: "An chi tiet",
    showDetails: "Hien chi tiet",
    showAddress: "Hien dia chi",
    hideAddress: "An dia chi",
    noAddressShared: "Chua co dia chi duoc chia se.",
    noMessagesYet: "Chua co tin nhan nao.",
    typeReply: "Nhap phan hoi va nhan Enter...",
  },
};

const es: AppCopy = {
  layout: {
    brandTagline: "Delicioso | Flexible | Facil",
    nav: {
      home: "Inicio",
      shop: "Tienda",
      community: "Comunidad",
      chat: "Chat",
    },
    signIn: "Iniciar sesion",
    profile: "Perfil",
    settings: "Ajustes",
    language: "Idioma",
    theme: "Modo",
    light: "Claro",
    dark: "Oscuro",
    languageNames: {
      en: "English",
      vi: "Tieng Viet",
      es: "Espanol",
    },
    signOut: "Cerrar sesion",
    signOutFailed: "No se pudo cerrar sesion",
  },
  common: {
    save: "Guardar",
    cancel: "Cancelar",
    close: "Cerrar",
    open: "Abrir",
    show: "Mostrar",
    hide: "Ocultar",
    delete: "Eliminar",
    clear: "Limpiar",
    done: "Listo",
    add: "Agregar",
    send: "Enviar",
    loading: "Cargando...",
    loadingChat: "Cargando chat...",
    working: "Trabajando...",
    searching: "Buscando...",
    adding: "Agregando...",
    deleting: "Eliminando...",
    sending: "Enviando...",
    you: "Tu",
    admin: "Admin",
    email: "Correo",
    password: "Contrasena",
    phone: "Telefono",
    fullName: "Nombre completo",
    address: "Direccion",
    deliveryAddress: "Direccion de entrega",
    noRecipient: "Sin destinatario",
    notes: "Notas",
    subtotal: "Subtotal",
    tax: "Impuesto",
    shipping: "Envio",
    total: "Total",
    status: "Estado",
    placed: "Realizado",
    items: "Articulos",
    description: "Descripcion",
    properties: "Propiedades",
    emptyMessage: "Mensaje vacio",
    noImage: "Sin imagen",
    noImageAvailable: "No hay imagen disponible",
    noDescriptionYet: "Todavia no hay descripcion.",
    shownCount: (shown: number, total: number) => `${shown} / ${total} mostrados`,
    orderId: (id: string) => `Pedido #${id.slice(0, 8)}`,
    customerId: (id: string) => `Cliente ${id.slice(0, 8)}`,
    orderCreated: (count: number) => `Pedido creado con ${count} articulo(s).`,
    orderPreviewTotal: (total: string) => `Total del pedido ${total}`,
    notesValue: (notes: string) => `Notas: ${notes}`,
    phoneValue: (phone: string) => `Telefono: ${phone}`,
    deleteListAria: (name: string) => `Eliminar ${name}`,
    removeItemAria: (name: string) => `Quitar ${name}`,
  },
  status: {
    pending: "Pendiente",
    confirmed: "Confirmado",
    shipped: "Enviado",
    out_for_delivery: "En reparto",
    delivered: "Entregado",
    cancelled: "Cancelado",
  },
  productImageField: {
    noImageSelected: "No hay imagen seleccionada",
    pasteImageUrl: "Pega aqui la URL de la imagen",
    uploading: "Subiendo...",
    uploadImage: "Subir imagen",
    clear: "Limpiar",
    helperText: "Pega una URL de imagen o sube un archivo a ImageKit.",
  },
  requireAdmin: {
    checking: "Verificando acceso de admin...",
  },
  home: {
    heroBadge: "Planificacion inteligente para las compras de cada dia",
    heroTitle: "Comprar comida se siente organizado, social y realmente util.",
    heroDescription:
      "Crea listas de compra, explora productos y comparte ideas con tu comunidad en una experiencia limpia. Menos friccion, menos olvidos y una mejor forma de planear comidas juntos.",
    startShopping: "Empezar a comprar",
    signInToStart: "Inicia sesion para empezar",
    exploreCommunity: "Explorar comunidad",
    statFastTitle: "Rapido",
    statFastDesc: "Listas rapidas",
    statSimpleTitle: "Simple",
    statSimpleDesc: "Exploracion limpia",
    statSocialTitle: "Social",
    statSocialDesc: "Ideas de la comunidad",
    flowTitle: "Flujo de esta semana",
    flowDescription: "Una mejor experiencia de compra desde la planificacion hasta el pedido.",
    live: "En vivo",
    step1Title: "1. Descubre productos",
    step1Desc: "Explora una cuadricula clara y agrega productos en segundos.",
    step2Title: "2. Crea tu lista",
    step2Desc: "Manten tu plan de compras organizado con listas personales.",
    step3Title: "3. Aprende de la comunidad",
    step3Desc: "Comparte recetas, consejos y hallazgos locales con otros compradores.",
    listsTitle: "Listas",
    listsDesc: "Mantente organizado",
    shopTitle: "Tienda",
    shopDesc: "Explora mas rapido",
    postsTitle: "Publicaciones",
    postsDesc: "Comparte ideas",
    card1Title: "Compras mas inteligentes",
    card1Desc: "Convierte notas sueltas en una lista clara que realmente puedas usar.",
    card2Title: "Capa comunitaria",
    card2Desc: "Descubre recetas, recomendaciones e ideas de personas que compran como tu.",
    card3Title: "Listo para crecer",
    card3Desc:
      "Una base solida para ampliar la marca, categorias, promociones y mejor contenido de producto.",
  },
  auth: {
    signIn: "Iniciar sesion",
    createAccount: "Crear cuenta",
    signUp: "Registrarse",
    checkEmailMessage: "Revisa tu correo para confirmar tu cuenta y luego inicia sesion.",
    somethingWentWrong: "Algo salio mal",
    authSettingsNote:
      "Configuracion de Supabase Auth: activa el proveedor Email y define Site URL + Redirect URLs para Netlify.",
  },
  community: {
    title: "Comunidad",
    subtitle: "Publicaciones publicas. Agrega comentarios o me gusta cuando tu flujo de Figma este listo.",
    createPost: "Crear publicacion",
    titlePlaceholder: "Titulo",
    bodyPlaceholder: "Comparte un consejo, receta u oferta...",
    post: "Publicar",
  },
  chat: {
    title: "Chat",
    subtitle: "Revisa tus chats de pedidos y elimina los mas antiguos.",
    orderRequestCreated: "Solicitud de pedido creada.",
    deliveryAddressShared: "Direccion de entrega compartida",
    newUpdate: "Nueva actualizacion",
    deleteConfirm: "Seguro que quieres eliminar este chat?",
    noChatsYet: "Todavia no hay chats",
    noChatsDescription: "Cuando envies una solicitud de pedido, aparecera aqui.",
    openChat: "Abrir chat",
  },
  shop: {
    title: "Tienda",
    subtitle: "Haz clic en cualquier articulo para ver todos los detalles.",
    searchPlaceholder: "Busca por nombre, categoria, descripcion, etiqueta o precio...",
    noProductsAvailable: "Todavia no hay productos disponibles.",
    noProductsMatch: "No hay productos que coincidan con tu busqueda.",
    itemDetails: "Detalles del articulo",
    addToCart: "Agregar al carrito",
    addsTo: "Se agrega a:",
    selectedListFallback: "Lista seleccionada",
    createListToStart: "Crea una lista para empezar a agregar articulos.",
    yourLists: "Tus listas",
    selectedList: "Lista seleccionada",
    selectAList: "Selecciona una lista...",
    defaultListName: "Mi lista",
    listName: "Nombre de la lista",
    noListsYet: "Todavia no hay listas.",
    openFullList: "Abrir lista completa",
    listItems: "Articulos de la lista",
    chooseListToView: "Elige una lista para ver sus articulos.",
    noListSelected: "No hay lista seleccionada.",
    listIsEmpty: "Esta lista esta vacia.",
    each: "cada uno",
    inList: (qty: number) => `${qty} en la lista`,
    deleteListTitle: "Eliminar lista",
    close: "Cerrar",
    deleteListConfirm: (name: string) => `Eliminar "${name}" y todos sus articulos?`,
    createOrSelectListFirst:
      "Crea o selecciona primero una lista en el panel derecho antes de agregar articulos.",
  },
  listDetail: {
    title: "Tu lista",
    subtitle: "Busca productos, agregalos al carrito y actualiza cantidades.",
    addItems: "Agregar articulos",
    searchProducts: "Buscar productos...",
    noMatches: "Sin resultados.",
    uncategorized: "Sin categoria",
    cartItems: "Articulos del carrito",
    noItemsYet: "Todavia no hay articulos. Busca arriba para agregar.",
    noPrice: "Sin precio",
    remove: "Quitar",
    orderTotal: "Total del pedido",
    taxRate: "Impuesto 9%",
    deliveryAddress: "Direccion de entrega",
    selectAddress: "Selecciona direccion...",
    noteToAdmin: "Nota para admin",
    notePlaceholder: "Nota opcional sobre entrega, sustituciones o tiempo...",
    sendingOrder: "Enviando pedido...",
    sendOrderRequest: "Enviar solicitud de pedido",
    listEmptyAlert: "Tu lista esta vacia.",
    addressRequiredAlert: "Agrega o selecciona primero una direccion de entrega.",
    couldNotCreateOrder: "No se pudo crear el pedido.",
    addressOption: (label: string, street: string, city: string) => `${label} - ${street}, ${city}`,
  },
  profile: {
    title: "Perfil",
    account: "Cuenta",
    saveProfile: "Guardar perfil",
    addAddress: "Agregar direccion",
    labelPlaceholder: "Etiqueta (Casa, Trabajo)",
    recipientNamePlaceholder: "Nombre del destinatario",
    phonePlaceholder: "Telefono",
    streetPlaceholder: "Direccion",
    apartmentPlaceholder: "Apartamento / unidad",
    cityPlaceholder: "Ciudad",
    statePlaceholder: "Estado",
    zipPlaceholder: "Codigo postal",
    countryPlaceholder: "Pais",
    deliveryNotesPlaceholder: "Notas de entrega",
    makeDefault: "Hacer esta mi direccion predeterminada",
    addAddressButton: "Agregar direccion",
    savedAddresses: "Direcciones guardadas",
    noAddressesYet: "Todavia no hay direcciones.",
    profileSaved: "Perfil guardado",
    cannotDeleteUsedAddress:
      "No puedes eliminar esta direccion porque ya se usa en uno o mas pedidos. Conservala para el historial o agrega una nueva y ponla como predeterminada.",
    deleteAddressConfirm: "Eliminar esta direccion guardada?",
    makeDefaultButton: "Hacer predeterminada",
    defaultBadge: "Predeterminada",
    addressFallback: "Direccion",
    homeLabel: "Casa",
  },
  orderDetail: {
    deleteConfirm: "Seguro que quieres eliminar este chat?",
    orderSummary: "Resumen del pedido",
    selectedDeliveryAddress: "Direccion de entrega seleccionada",
    orderChat: "Chat del pedido",
    adminDeletedTitle: "Este chat fue eliminado por admin.",
    adminDeletedBody: "Aun puedes revisarlo aqui. Quieres eliminarlo tambien?",
    deleteThisChat: "Eliminar este chat",
    addressChip: (label: string) => `Direccion: ${label}`,
    sendAddressTitle: "Enviar esta direccion al chat",
    typeMessage: "Escribe un mensaje...",
    noMessagesYet: "Todavia no hay mensajes.",
  },
  admin: {
    dashboardTitle: "Panel de admin",
    dashboardSubtitle: "Gestiona productos y chats reales de pedidos de clientes.",
    tabChat: "Chat",
    tabItems: "Articulos",
    addProduct: "Agregar producto",
    productName: "Nombre del producto",
    productImage: "Imagen del producto",
    newProductImage: "Imagen de producto nueva",
    priceUsd: "Precio (USD)",
    tags: "Etiquetas",
    tagsPlaceholder: "Fresco, Organico, 1 lb",
    tagsHint: "Separa cada propiedad con una coma.",
    description: "Descripcion",
    descriptionPlaceholder: "Una descripcion para este articulo",
    addProductButton: "Agregar producto",
    products: "Productos",
    searchItemsPlaceholder: "Buscar por nombre, etiqueta, descripcion o precio...",
    noProductsYet: "Todavia no hay productos.",
    noProductsMatch: "No hay productos que coincidan con tu busqueda.",
    productDescriptionPlaceholder: "Descripcion del producto",
    pricePlaceholder: "Precio",
    edit: "Editar",
    inStock: "En stock",
    outOfStock: "Agotado",
    customerChats: "Chats de clientes",
    customerChatsSubtitle:
      "Busca por nombre del cliente o pedido y luego usa filtros por fecha y total.",
    select: "Seleccionar",
    markShipped: "Marcar enviado",
    searchCustomersPlaceholder: "Buscar nombre del cliente o pedido #...",
    openFilters: "Abrir filtros",
    advancedFilters: "Filtros avanzados",
    fromDate: "Desde",
    toDate: "Hasta",
    minTotal: "Total minimo",
    maxTotal: "Total maximo",
    noOrderChats: "Todavia no hay chats de pedidos.",
    noChatsMatch: "Ningun chat coincide con los filtros actuales.",
    selectChatFirst: "Selecciona al menos un chat primero.",
    confirmMarkSelectedShipped:
      "Seguro que quieres marcar los chats seleccionados como enviados?",
    confirmHideSelectedChats:
      "Seguro que quieres quitar los chats seleccionados solo del panel de admin?",
    adminNotFound: "No se pudo encontrar al admin conectado.",
    confirmMarkCurrentShipped: "Seguro que quieres marcar este pedido como enviado?",
    imageUploadFailed: "Fallo la subida de imagen.",
    loadingChat: "Cargando chat...",
    orderNotFound: "Pedido no encontrado.",
    orderSummary: "Resumen del pedido",
    hideDetails: "Ocultar detalles",
    showDetails: "Mostrar detalles",
    showAddress: "Mostrar direccion",
    hideAddress: "Ocultar direccion",
    noAddressShared: "Todavia no se compartio direccion.",
    noMessagesYet: "Todavia no hay mensajes.",
    typeReply: "Escribe una respuesta y presiona Enter...",
  },
};

const copyByLanguage: Record<Language, AppCopy> = {
  en,
  vi,
  es,
};

const localeByLanguage: Record<Language, string> = {
  en: "en-US",
  vi: "vi-VN",
  es: "es-ES",
};

function getSavedLanguage(): Language {
  if (typeof window === "undefined") return "en";
  const saved = window.localStorage.getItem(LANGUAGE_STORAGE_KEY);
  return saved === "vi" || saved === "es" ? saved : "en";
}

function getSavedTheme(): ThemeMode {
  if (typeof window === "undefined") return "light";
  const saved = window.localStorage.getItem(THEME_STORAGE_KEY);
  if (saved === "dark" || saved === "light") return saved;
  return window.matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light";
}

function parseOrderCreatedCount(body: string | null) {
  if (!body) return null;

  const normalized = body.trim();
  const tokenMatch = normalized.match(/^order_created:(\d+)$/i);
  if (tokenMatch) return Number(tokenMatch[1]);

  const legacyPatterns = [
    /^Order created with (\d+) item\(s\)\.?$/i,
    /^Don hang duoc tao voi (\d+) mat hang\.?$/i,
    /^Pedido creado con (\d+) articulo\(s\)\.?$/i,
  ];

  for (const pattern of legacyPatterns) {
    const match = normalized.match(pattern);
    if (match) return Number(match[1]);
  }

  return null;
}

type AppSettingsContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  theme: ThemeMode;
  setTheme: (theme: ThemeMode) => void;
  copy: AppCopy;
  locale: string;
  formatCurrency: (cents: number) => string;
  formatDateTime: (value: string | number | Date) => string;
  formatStatus: (status: string) => string;
  formatStoredMessage: (messageType: string, body: string | null) => string;
};

const AppSettingsContext = createContext<AppSettingsContextValue | null>(null);

export function AppSettingsProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(getSavedLanguage);
  const [theme, setTheme] = useState<ThemeMode>(getSavedTheme);

  const copy = copyByLanguage[language];
  const locale = localeByLanguage[language];

  useEffect(() => {
    window.localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    window.localStorage.setItem(THEME_STORAGE_KEY, theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo<AppSettingsContextValue>(() => {
    const currencyFormatter = new Intl.NumberFormat(locale, {
      style: "currency",
      currency: "USD",
    });
    const dateTimeFormatter = new Intl.DateTimeFormat(locale, {
      dateStyle: "medium",
      timeStyle: "short",
    });

    return {
      language,
      setLanguage,
      theme,
      setTheme,
      copy,
      locale,
      formatCurrency: (cents: number) => currencyFormatter.format(cents / 100),
      formatDateTime: (value: string | number | Date) =>
        dateTimeFormatter.format(new Date(value)),
      formatStatus: (status: string) =>
        copy.status[status as keyof AppCopy["status"]] ?? status,
      formatStoredMessage: (messageType: string, body: string | null) => {
        if (messageType === "system") {
          const count = parseOrderCreatedCount(body);
          if (count !== null) return copy.common.orderCreated(count);
        }

        return body?.trim() || copy.common.emptyMessage;
      },
    };
  }, [copy, language, locale, theme]);

  return <AppSettingsContext.Provider value={value}>{children}</AppSettingsContext.Provider>;
}

export function useAppSettings() {
  const context = useContext(AppSettingsContext);
  if (!context) {
    throw new Error("useAppSettings must be used within AppSettingsProvider");
  }
  return context;
}
